# -*- coding: utf-8 -*-
{
    "name": "RJE :: Install RJE Addons",
    "summary": "",
    "version": "8.0.1.0.0",
    "category": "Uncategorized",
    "description": """


    """,
    "website": "http://odoo8.rjemc.com:8069",
    "author": "Phongyanon Y.,",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        # Standard Module for most SMEs.
        "account_billing",
        "account_bank_receipt",
        "account_bank_receipt_cancel_reason",
        "account_invoice_cancel_reason",
        "account_voucher_cancel_reason",
        "hr_expense_cancel_reason",
        "account_debitnote",
        "account_invoice_create_payment",
        "account_cancel_reversal",
        "res_currency_rate_ext",
        "hr_expense_auto_invoice",
        "account_voucher_net_payment",
        "purchase_invoice_plan",
        "sale_invoice_plan",
        # Thai Localization Module
        "l10n_th_fields",
        "l10n_th_address",
        "l10n_th_amount_text",
        "l10n_th_account",
        "l10n_th_account_pnd_form",
        "l10n_th_account_deduction",
        "l10n_th_account_tax_detail",
        "l10n_th_tax_report",
        "l10n_th_doctype_base",
        "l10n_th_doctype_order",
        "l10n_th_doctype_stock",
        "l10n_th_doctype_bank_receipt",
        "l10n_th_doctype_invoice",
        "l10n_th_doctype_voucher",
        # Additional Module
        "purchase_split_quote2order",
        "sale_split_quote2order",
        "account_auto_fy_sequence",
        "jasper_reports",
        "account_invoice_check_tax_lines_hook",
        "account_voucher_writeoff_move_line_get_hooks",
        "account_voucher_action_move_line_create_hooks",
        "sale_wizard_make_invoices_hooks",
        "sale_order_action_invoice_create_hooks",
        "sale_order_make_invoice_hooks",
        "sale_order_line_prepare_order_line_invoice_line_hooks",
        "sale_invoice_line_percentage",
        "purchase_invoice_line_percentage",
        "hr_expense_sequence",
        "account_voucher_cancel_hooks",
        "hr_salary",
        "account_invoice_cancel_hooks",
        "account_refund_linked_invoice",
        "account_billing_hook_recompute_vline",
    ],
    'pre_init_hook': 'pre_init_hook',
}
